services:
  alento-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alento-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      PORT: 4000
      HOST: 0.0.0.0
      MONGO_URI: ${MONGO_URI_DOCKER:-mongodb://host.docker.internal:27017/ALENTO?directConnection=true}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

